export const ACTIONTYPES = {
  FETCH_PENDING: "FETCH_PENDING",
  FETCH_FULFILLED: "FETCH_FULFILLED",
  FETCH_REJECTED: "FETCH_REJECTED",
};
export const CHECKOUT_ACTIONTYPES = {
  ADD_CHECKOUT: "ADD_CHECKOUT",
};
