import Head from 'next/head'
import {Inter} from 'next/font/google'
import React from "react";

const inter = Inter({subsets: ['latin']})
import Product from '@/components/Product'
import ProductsProvider from '@/context/ProductsProvider'
import UserProvider from '@/context/UserProvider'
import {Provider} from "react-redux";
import {store} from "@/redux/store";
import {ThemeProvider} from "@mui/material";
import {theme} from '@/theme'

export default function Home() {
  return (
    <>
      <Head>
        <title>My app</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Provider store={store}>
        <ThemeProvider theme={theme}>
            <UserProvider>
              <ProductsProvider>
                <Product/>
              </ProductsProvider>
            </UserProvider>
        </ThemeProvider>
      </Provider>
    </>
  )
}
